### ISSUE TITLE
jsGraph.com

### ISSUE THREAD

**Issue by LeoColomb** [zingchart/awesome-charting#4]
Hey!

Good awesome list!
Do you know [jsGraph.com](http://www.jsgraphs.com/)?
Not sure where to add it to the list, or even if it's relevant.

Thanks! :smile:

**Comment by mike-schultz** [comment]
Hi there!

I have seen jsGraph before, but adding to this list would be a bit redundant since both list similar content. Feel free to contribute any charting libraries themselves to the list.
